### ISSUE TITLE
Won't stay at manual / none

### ISSUE THREAD

**Issue by dlysnes** [robbinjanssen/home-assistant-ojmicroline-thermostat#11]
## Detailed description
Thanx for creating this! Just installed via HACS and installation went well. I have a microtemp mwd5 thermostat from micromatic. 
When adjusting temperature, the thermostat will always revert to comfort mode, and them resume plan after 4 hours. When i try to set none /manual mode it will revert to 20c, and then back to comfort. I wish to control everything manually 

## Context
Trying to adjust temperature 

## Diagnostics

The thermostat will after a while switch over to auto / comfort. 
```json
"Copy here the code or upload the file"
```

**Comment by robbinjanssen** [comment]
Yes this is the current implementer behavior, when setting temp it puts it in ‘comfort mode’ and resets to the schedule after 4 hours. I could change it to set it manual but then it will never resume schedule automatically (this is the default behavior of the thermostat). I think we need some more configuration options, ill see what I can do when I return from holiday👍🏻

**Comment by dlysnes** [comment]
Thanx :) Yes, a config option would be nice for this. I've been using the node-red flow since the start, and manual control is working fine there. I do however really like your implementation and the fact that it's easily added. The node-red flow requires more manual follow-up.
I use priceanalyzer to control this thermostat, and that's why manual control is essential. I also added a virtual power sensor to measure power when heating is 'on'. I'm happy to test whatever you do here, as I'm an old developer myself ;)

**Comment by robbinjanssen** [comment]
So this is the code responsible: https://github.com/robbinjanssen/home-assistant-ojmicroline-thermostat/blob/main/custom_components/ojmicroline_thermostat/climate.py#L218-L222

Im thinking the following:
- First get the current regulation mode, if it is in comfort or manual, leave it like that and update the temp.
- If it is in another mode, use the mode that we will introduce in a config (any idea's for a name?) and then set the temp

Also when using comfort mode, we need to provide a time (e.g. put the thermostat in comfort mode for x hours, 4 is currently [hardcoded](https://github.com/robbinjanssen/python-ojmicroline-thermostat/blob/main/ojmicroline_thermostat/requests/update_group_request.py#L54-L55)) Maybe this should be a config option as well? Any thoughts?

**Comment by robbinjanssen** [comment]
Try downloading v1.1.0, I think the default behaviour should work for you now :)
If not, feel free to reopen!

**Comment by dlysnes** [comment]
Hey! Will do!
Btw, when it comes to default behavior in app (my app is microtemp) it will add 4 hours timer when I manually change room temp, but it stays on manual if i change temo on a single thermostat.

**Comment by dlysnes** [comment]
Yep, looks good. Stays in manual in app. Thanx a bunch!
![Screenshot_2023-01-29-21-33-16-04_b8e0f1c9f46c396bf60ba68210414932](https://user-images.githubusercontent.com/3194140/215354386-934cfc34-6ffe-4be1-a1a5-77b6b5633a09.jpg)

**Comment by robbinjanssen** [comment]
Glad to hear its working!

**Comment by dlysnes** [comment]
Hm, seems we still have an issue. In manual mode yhe thermostat stays in status "auto". This leads to Priceanalyzer failing to set temperature. When i try to set hvac_mode "heat" it fails with this error:
![Screenshot_2023-02-08-18-48-29-76_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/3194140/217630285-8d70663b-6f8c-4362-aa72-d6f5cb016823.jpg)
Is it possible to set this somehow?

**Comment by dlysnes** [comment]
> Hm, seems we still have an issue. In manual mode the thermostat stays in status "auto". This leads to Priceanalyzer failing to set temperature. When i try to set hvac_mode "heat" it fails with this error: ![Screenshot_2023-02-08-18-48-29-76_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/3194140/217630285-8d70663b-6f8c-4362-aa72-d6f5cb016823.jpg) Is it possible to set this somehow?

Never mind, I updated Priceanalyzer blueprint instead for now ;)

**Comment by robbinjanssen** [comment]
That is because it is nog possible to force the thermostat to start heating. 

It just switches on/off based on the temperature, at least in my case. In other words, to my knowledge there is no api endpoint on the oj microline side to 'heat'. 

Setting the mode to manual with a target temperature above the current temperature will eventually result in hvac mode heat as soon as your thermostat actually starts heating. Thats why setting the hvac mode has no use. I'll see if I can at least remove the error 😀
