### ISSUE TITLE
Failed to call service climate/set_temperature. [Error/Timeout] occurred while communicating with the OJ Microline API.

### ISSUE THREAD

**Issue by gessl** [robbinjanssen/home-assistant-ojmicroline-thermostat#139]
I on occasion get the following two error messages:

Failed to call service climate/set_temperature. Error occurred while communicating with the OJ Microline API.

and

Failed to call service climate/set_temperature. Timeout occurred while communicating with the OJ Microline API.

Steps to produce is simply to change the set temperature or issue other commands via the card on the dashboard. It's unclear to me when precisely it happens, but it happens fairly regularly for me (I'll try to narrow this down.)

**Comment by robbinjanssen** [comment]
@gessl maybe add a [ping sensor](https://www.home-assistant.io/integrations/ping/) to your thermostat, see if the wifi is stable?

**Comment by robbinjanssen** [comment]
I think this might be related to #140

**Comment by gessl** [comment]
Sounds good. I'll be testing!
