### ISSUE TITLE
Integration not loaded in version 2024.7.1

### ISSUE THREAD

**Issue by Floriszz** [robbinjanssen/home-assistant-ojmicroline-thermostat#211]
## Detailed description

The error says that something wrong about import_module.
Same as other integrations HACS and native;
Google Nest: https://github.com/home-assistant/core/issues/121521
HACS pod_point : https://github.com/home-assistant/core/issues/121284
HACS omnic convertor: No issue raised jet

## Context

The integration won't load anymore after update from 2026.6.4 to 2024.7.1

## Diagnostics

Sorry, because I did a restore I can not get to the logs anymore

**Comment by Floriszz** [comment]
Seems related with;
https://github.com/home-assistant/core/issues/119223

**Comment by robbinjanssen** [comment]
I'm on 2024.7.2 and everything is working fine, sorry but without logs I cannot do anything :/

**Comment by Floriszz** [comment]
Thanks for the update! I saw the 2024.7.2 version advertising, but this time I though I wait a bit to see if others don't have problems😎.
So will give it a try now🤞

**Comment by robbinjanssen** [comment]
Assuming this is fixed, i'm closing this
